springdoc:
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true
server:
  tomcat:
    max-http-form-post-size: 50MB
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
